"""
FastAPI Server Backend for Ollama Agents Web Dashboard.
"""

import os
import json
import asyncio
from typing import List, Optional, Dict, Any
from pathlib import Path
from fastapi import FastAPI, HTTPException, BackgroundTasks, UploadFile, File
from fastapi.staticfiles import StaticFiles
from fastapi.responses import HTMLResponse, StreamingResponse
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel

from ollama_agents import Agent, GoalRegistry, MemoryStore

app = FastAPI(title="Ollama Agents Web Dashboard", version="0.6.0")

# CORS setup
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# ── Pydantic Request Schemas ───────────────────────────────────────────────────
class SingleTaskRequest(BaseModel):
    prompt: str
    model: str = "deepseek-r1:8b"
    max_turns: int = 25

class FollowupRequest(BaseModel):
    prompt: str
    auto_run: bool = True

class CreateGoalRequest(BaseModel):
    prompt: str
    model: str = "deepseek-r1:8b"

class PullModelRequest(BaseModel):
    model_tag: str

class AddNodeRequest(BaseModel):
    host_url: str
    name: Optional[str] = None

# Global active model pull status tracker
PULLING_MODELS: Dict[str, Any] = {}

# ── API Endpoints ─────────────────────────────────────────────────────────────
@app.get("/api/cluster/nodes")
def api_get_cluster_nodes():
    """Get status of all connected laptops/nodes in the distributed cluster and aggregated models."""
    from ollama_agents.cluster import cluster_manager
    return cluster_manager.refresh_cluster_status()

@app.post("/api/cluster/nodes/add")
def api_add_cluster_node(req: AddNodeRequest):
    """Connect a secondary laptop/computer running Ollama to the distributed agent cluster."""
    from ollama_agents.cluster import cluster_manager
    node = cluster_manager.add_node(host_url=req.host_url, name=req.name)
    if node.is_active:
        return {"status": "success", "message": f"Successfully connected secondary laptop node '{node.name}' ({node.host_url})!", "node": node.__dict__}
    return {"status": "warning", "message": f"Added node '{node.name}' ({node.host_url}), but could not reach Ollama API. Ensure 'OLLAMA_HOST=0.0.0.0' is set on secondary machine.", "node": node.__dict__}
@app.get("/api/workspace/files")
def api_list_workspace_files():
    """List all project files, code, and reports generated by the agent in ~/ollama_workspace/."""
    workspace_dir = Path.home() / "ollama_workspace"
    workspace_dir.mkdir(parents=True, exist_ok=True)
    files_list = []
    for path in sorted(workspace_dir.rglob("*")):
        if path.is_file():
            rel = str(path.relative_to(workspace_dir)).replace("\\", "/")
            files_list.append({
                "name": path.name,
                "relative_path": rel,
                "full_path": str(path),
                "url": f"/workspace/{rel}",
                "size_bytes": path.stat().st_size,
            })
    return {"workspace_path": str(workspace_dir), "files": files_list}

@app.post("/api/goals/{goal_id}/followup")
def api_add_goal_followup(goal_id: str, req: FollowupRequest, background_tasks: BackgroundTasks):
    """Add a follow-up question or new sub-task to an existing goal and optionally execute it immediately."""
    registry = GoalRegistry()
    goal = registry.get_goal(goal_id)
    if not goal:
        raise HTTPException(status_code=404, detail="Goal not found")

    new_task = registry.add_followup_task(goal_id, req.prompt)
    if not new_task:
        raise HTTPException(status_code=500, detail="Failed to add follow-up task")

    if req.auto_run:
        # Trigger background execution for the follow-up task
        res = api_run_goal_task(goal_id=goal_id, background_tasks=background_tasks, auto_continue=True)
        return {"status": "success", "task": new_task.__dict__, "execution": res}

    return {"status": "success", "task": new_task.__dict__, "message": "Follow-up task appended to goal."}
@app.get("/api/models")
def api_list_models():
    """List all available Ollama models installed locally on the machine."""
    import ollama
    try:
        models_data = ollama.list()
        raw_models = getattr(models_data, 'models', models_data.get('models', []))
        names = []
        for m in raw_models:
            name = getattr(m, 'model', getattr(m, 'name', None))
            if not name and isinstance(m, dict):
                name = m.get('model', m.get('name'))
            if name:
                names.append(str(name))
        return {"models": names if names else ["deepseek-r1:8b", "llama3.1:latest"], "pulling": list(PULLING_MODELS.keys())}
    except Exception as e:
        return {"models": ["deepseek-r1:8b", "llama3.1:latest"], "error": str(e), "pulling": list(PULLING_MODELS.keys())}

@app.get("/api/system/stats")
def api_system_stats():
    """Get live RAM/CPU utilization and active subagent execution counts."""
    from ollama_agents.memory_manager import memory_manager
    return memory_manager.get_system_stats()

@app.post("/api/system/gc")
def api_trigger_gc():
    """Force garbage collection to clean up memory."""
    from ollama_agents.memory_manager import memory_manager
    return memory_manager.force_garbage_collection()

@app.post("/api/models/pull")
def api_pull_model(req: PullModelRequest, background_tasks: BackgroundTasks):
    """Pull a new GGUF model from Hugging Face / Ollama in the background."""
    model_tag = req.model_tag.strip()
    if not model_tag:
        raise HTTPException(status_code=400, detail="Model tag cannot be empty.")

    if model_tag in PULLING_MODELS:
        return {"status": "already_pulling", "message": f"Model '{model_tag}' is already being pulled in the background."}

    def _pull():
        PULLING_MODELS[model_tag] = {"status": "downloading"}
        try:
            import ollama
            logger.info("Pulling model '%s' into local Ollama...", model_tag)
            ollama.pull(model_tag)
            logger.info("Successfully pulled model '%s'!", model_tag)
        except Exception as e:
            logger.error("Failed to pull model '%s': %s", model_tag, e)
        finally:
            PULLING_MODELS.pop(model_tag, None)

    background_tasks.add_task(_pull)
    return {"status": "started", "message": f"Download started for model '{model_tag}'. You can track progress or refresh installed models once done."}

@app.get("/api/models/search-hf")
def api_search_hf_models(query: str):
    """Search Hugging Face Hub for GGUF models compatible with local Ollama."""
    from ollama_agents.model_selector import search_huggingface_models
    results = search_huggingface_models(query=query)
    return {"query": query, "results": results}

@app.get("/api/models/trending-hf")
def api_trending_hf_models():
    """Fetch daily trending GGUF models from Hugging Face Hub."""
    from ollama_agents.model_selector import fetch_trending_hf_models
    results = fetch_trending_hf_models()
    return {"results": results}

@app.post("/api/upload")
async def api_upload_file(file: UploadFile = File(...)):
    """Upload a file or image for analysis, editing, or reference by the agent."""
    try:
        upload_dir = Path.home() / "ollama_workspace" / "uploads"
        upload_dir.mkdir(parents=True, exist_ok=True)
        
        # Sanitize filename
        safe_filename = Path(file.filename).name
        dest_path = upload_dir / safe_filename
        
        contents = await file.read()
        dest_path.write_bytes(contents)
        
        rel_path = f"uploads/{safe_filename}"
        return {
            "status": "success",
            "filename": safe_filename,
            "filepath": rel_path,
            "full_path": str(dest_path),
            "size": len(contents),
            "message": f"File '{safe_filename}' uploaded successfully to '{rel_path}'."
        }
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to upload file: {e}")

@app.get("/api/goals")
def api_list_goals():
    """List all long-horizon goals."""
    registry = GoalRegistry()
    goals = registry.list_goals()
    return [{
        "goal_id": g.id,
        "title": g.description,
        "model": g.agent_name,
        "created_at": g.created,
        "progress_pct": g.progress_pct,
        "final_summary": getattr(g, 'final_summary', ''),
        "tasks_count": len(g.tasks),
        "tasks": [t.__dict__ for t in g.tasks]
    } for g in goals]

@app.post("/api/goals/create")
def api_create_goal(req: CreateGoalRequest):
    """Decompose and save a new goal."""
    registry = GoalRegistry()
    goal = registry.create_goal(req.prompt, model=req.model)
    return {"status": "success", "goal": goal.__dict__, "tasks": [t.__dict__ for t in goal.tasks]}

# Global active execution registry for kill switch
ACTIVE_EXECUTIONS: Dict[str, Any] = {}

@app.post("/api/goals/{goal_id}/run")
def api_run_goal_task(goal_id: str, background_tasks: BackgroundTasks, auto_continue: bool = True):
    """Trigger goal tasks in the background. If auto_continue=True, automatically proceeds through all remaining pending sub-tasks."""
    registry = GoalRegistry()
    goal = registry.get_goal(goal_id)
    if not goal:
        raise HTTPException(status_code=404, detail="Goal not found")

    next_task = goal.next_task
    if not next_task:
        return {"status": "completed", "message": "All tasks for this goal are already complete."}

    if goal_id in ACTIVE_EXECUTIONS:
        return {"status": "already_running", "message": f"Goal {goal_id} is already running in the background."}

    def _execute():
        ACTIVE_EXECUTIONS[goal_id] = {"status": "running"}
        try:
            from ollama_agents.tools import web_search, get_realtime_market_quote, write_file, read_file, run_terminal, run_python, delegate_subagent, rag_add_knowledge, rag_search, generate_image_sd_forge, edit_image_sd_forge, edit_image, generate_video_comfyui, github_clone_repo, github_create_branch, github_commit_and_push, github_create_pull_request, github_status
            
            while True:
                # Re-fetch latest goal state
                current_goal = registry.get_goal(goal_id)
                if not current_goal:
                    break

                curr_task = current_goal.next_task
                if not curr_task:
                    # All tasks done! Generate overall final synthesis summary
                    if not current_goal.final_summary:
                        try:
                            model_name = getattr(current_goal, 'agent_name', getattr(current_goal, 'model', 'deepseek-r1:8b'))
                            if model_name == "AutonomousAgent" or not model_name:
                                model_name = "deepseek-r1:8b"
                            agent = Agent(model=model_name, max_turns=10)
                            
                            subtask_outputs = []
                            for t in current_goal.tasks:
                                subtask_outputs.append(f"- Sub-task: {t.description}\n  Result: {t.output[:400]}")
                            
                            summary_prompt = (
                                f"Goal: {current_goal.description}\n\n"
                                f"All {len(current_goal.tasks)} session sub-tasks have been completed. Here are the outputs:\n"
                                + "\n".join(subtask_outputs) +
                                "\n\nProvide a comprehensive, high-level final summary and overall conclusion for this completed goal."
                            )
                            summary_res = agent.run(summary_prompt)
                            registry.save_final_summary(goal_id, summary_res)
                        except Exception as sum_err:
                            logger.warning("Final summary synthesis failed: %s", sum_err)
                    break

                model_name = getattr(current_goal, 'agent_name', getattr(current_goal, 'model', 'deepseek-r1:8b'))
                if model_name == "AutonomousAgent" or not model_name:
                    model_name = "deepseek-r1:8b"

                memory = MemoryStore(agent_name="AssistantAgent")
                agent = Agent(
                    model=model_name,
                    tools=[write_file, read_file, run_terminal, run_python, web_search, get_realtime_market_quote, delegate_subagent, rag_add_knowledge, rag_search, generate_image_sd_forge, edit_image_sd_forge, edit_image, generate_video_comfyui, github_clone_repo, github_create_branch, github_commit_and_push, github_create_pull_request, github_status],
                    memory=memory,
                    max_turns=25
                )
                
                # Execute current session sub-task
                agent.run_goal(goal_id)

                if not auto_continue or goal_id not in ACTIVE_EXECUTIONS:
                    break

        except Exception as e:
            curr_g = registry.get_goal(goal_id)
            if curr_g and curr_g.next_task:
                registry.fail_task(goal_id, curr_g.next_task.id, reason=str(e))
        finally:
            ACTIVE_EXECUTIONS.pop(goal_id, None)

    background_tasks.add_task(_execute)
    return {"status": "started", "message": f"Execution started for goal {goal_id} (Auto-continue: {auto_continue})"}

@app.post("/api/goals/{goal_id}/kill")
def api_kill_goal_execution(goal_id: str):
    """Kill active background execution for a specific goal and reset task state safely."""
    ACTIVE_EXECUTIONS.pop(goal_id, None)
    registry = GoalRegistry()
    goal = registry.get_goal(goal_id)
    
    # Mark in-progress tasks as cancelled/pending in registry
    if goal:
        for t in goal.tasks:
            if t.status == "in_progress":
                registry.fail_task(goal_id, t.id, reason="Execution stopped by user Kill Switch")

    return {"status": "killed", "message": f"Killed active execution and reset state for goal {goal_id}"}

@app.delete("/api/goals/{goal_id}")
def api_delete_goal(goal_id: str):
    """Permanently delete a goal, terminate any in-flight background execution, and clean up stored state."""
    # Instantly stop active background execution loop if running
    ACTIVE_EXECUTIONS.pop(goal_id, None)
    
    registry = GoalRegistry()
    success = registry.delete_goal(goal_id)
    if not success:
        raise HTTPException(status_code=404, detail="Goal not found or could not be deleted")
    return {"status": "success", "message": f"Goal '{goal_id}' deleted successfully."}

@app.post("/api/tasks/kill-all")
def api_kill_all_executions():
    """Emergency Kill Switch: Stop all active goal & single task executions and reset state."""
    registry = GoalRegistry()
    goals = registry.list_goals()
    killed_count = 0

    for goal in goals:
        for t in goal.tasks:
            if t.status == "in_progress":
                registry.fail_task(goal.id, t.id, reason="Stopped by Emergency Kill-All Switch")
                killed_count += 1

    ACTIVE_EXECUTIONS.clear()
    return {"status": "success", "message": f"Emergency Kill Switch activated. Cleared {killed_count} active tasks."}

@app.post("/api/task/run")
def api_run_single_task(req: SingleTaskRequest):
    """Run a single task synchronously and return the result."""
    try:
        from ollama_agents.tools import web_search, get_realtime_market_quote, write_file, read_file, run_terminal, run_python, delegate_subagent, rag_add_knowledge, rag_search, generate_image_sd_forge, edit_image_sd_forge, edit_image, generate_video_comfyui, github_clone_repo, github_create_branch, github_commit_and_push, github_create_pull_request, github_status
        memory = MemoryStore(agent_name="AssistantAgent")
        agent = Agent(
            model=req.model,
            tools=[write_file, read_file, run_terminal, run_python, web_search, get_realtime_market_quote, delegate_subagent, rag_add_knowledge, rag_search, generate_image_sd_forge, edit_image_sd_forge, edit_image, generate_video_comfyui, github_clone_repo, github_create_branch, github_commit_and_push, github_create_pull_request, github_status],
            memory=memory,
            max_turns=req.max_turns
        )
        result = agent.run(req.prompt)
        return {"status": "completed", "result": result}
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

@app.get("/api/reflections")
def api_get_reflections(limit: int = 10):
    """Get stored agent self-reflections."""
    mem = MemoryStore()
    return mem.get_reflections(limit=limit)

# ── Serve Dashboard UI & Workspace Media Static Files ────────────────────────
WORKSPACE_DIR = Path.home() / "ollama_workspace"
WORKSPACE_DIR.mkdir(parents=True, exist_ok=True)
app.mount("/workspace", StaticFiles(directory=str(WORKSPACE_DIR)), name="workspace")

STATIC_DIR = os.path.join(os.path.dirname(__file__), "static")
if not os.path.exists(STATIC_DIR):
    os.makedirs(STATIC_DIR)

@app.get("/", response_class=HTMLResponse)
def index():
    html_file = os.path.join(STATIC_DIR, "index.html")
    if os.path.exists(html_file):
        with open(html_file, "r", encoding="utf-8") as f:
            return f.read()
    return "<h1>Ollama Agents Web Dashboard - Front end loading...</h1>"
